### ISSUE TITLE
Use partition by

### ISSUE THREAD

**Issue by StuartFergusonVme** [Sergej-Popov/event-store-projection-testing#1]
Just started using this library to unit test our projections and working perfect so far :)

One drawback is we use .partitionBy in some of our projctions which this library does not support.

Is this something that can be easily added in ?

**Comment by Sergej-Popov** [comment]
This is a very thin wrapper on a chunk of source code taken directly from EventStore itself.  I cannot remember which version of EventStre this was based on, but looking inside I can see `partitionBy` is there so, in theory, it should be working. https://github.com/Sergej-Popov/event-store-projection-testing/blob/master/prelude/Projections.js#L511

Do you have an example projection? What errors you are getting?

**Comment by StuartFergusonVme** [comment]
Thanks @Sergej-Popov  ill give that a try at a future time.  Will close this issue for now.
