### ISSUE TITLE
Testing TransformBy in projections

### ISSUE THREAD

**Issue by StuartFergusonVme** [Sergej-Popov/event-store-projection-testing#2]
I am attempting to use this library to test out a projection with a transformBy at the end.

I have added the following at the top of the projection

`var transformBy = transformBy || require('event-store-projection-testing').scope.transformBy;`

and have this in my actual projection

```
.transformBy(function (s) {
        s.eventMessage = 'Transformed';
        return {
            "test" : "Tranformed State"
        };
    }
```

But when trying to verify this in my test I can see no way of doing it.

Can you confirm the library indeed supports transformBy and if it does how I go about testing it?

**Comment by Sergej-Popov** [comment]
Hey, I've not looked into ES for years now, so things may have changed as this is based on an old version. `transformBy` should be supported though, did you try asserting using  `projection.getState().test` or even just dump state into a log and see what you have there `console.log(JSON.stringify( projection.getState()))` ? Is your projection actually working as you expect in the ES?

If you provide a sample projection with a test in a repo or CodePen I might be able to find some time to have a look.

**Comment by StuartFergusonVme** [comment]
I have managed to get this working but requires a small code change to _util.js_.  If you want I can fork the repo and make the change then create a Pull Request to merge it in.

**Comment by Sergej-Popov** [comment]
Great, thanks @StuartFergusonVme . PR is merged. [2.0.1](https://www.npmjs.com/package/event-store-projection-testing/v/2.0.1) is released.
